# Generated by Django 3.2.25 on 2025-05-26 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_flashcard_next_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
