# Generated by Django 3.2.25 on 2025-06-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reviewlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='ease_factor',
            field=models.IntegerField(default=250),
        ),
    ]
