# Generated by Django 3.2.25 on 2025-06-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_flashcard_ease_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_learning',
            field=models.BooleanField(default=True),
        ),
    ]
